### ISSUE TITLE
"No compatible client available. Please change your scope" Crash

### ISSUE THREAD

**Issue by dheeraj2dj** [truecaller/flutter-sdk#3]
This crash is happening when there is no Truecaller app installed. I have added checks on `isUsable` and also checking if if truecaller app is installed or not using [device_apps](https://pub.dev/packages/device_apps).

Please help me understand this crash, and how to resolve it.
Thanks!

```
E/AndroidRuntime(  818): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1276, result=0, data=null} to activity {buzz.praja.app/buzz.praja.app.MainActivity}: java.lang.RuntimeException: No compatible client available. Please change your scope
E/AndroidRuntime(  818): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
E/AndroidRuntime(  818): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138)
E/AndroidRuntime(  818): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(  818): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(  818): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(  818): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
E/AndroidRuntime(  818): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(  818): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(  818): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/AndroidRuntime(  818): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  818): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(  818): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
E/AndroidRuntime(  818): Caused by: java.lang.RuntimeException: No compatible client available. Please change your scope
E/AndroidRuntime(  818): 	at com.truecaller.android.sdk.TruecallerSDK.onActivityResultObtained(TruecallerSDK.java:198)
E/AndroidRuntime(  818): 	at com.truecallersdk.TruecallerSdkPlugin$onAttachedToActivity$1.onActivityResult(TruecallerSdkPlugin.kt:196)
E/AndroidRuntime(  818): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(  818): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(  818): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime(  818): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:704)
E/AndroidRuntime(  818): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:509)
E/AndroidRuntime(  818): 	at android.app.Activity.dispatchActivityResult(Activity.java:8292)
E/AndroidRuntime(  818): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5090)
E/AndroidRuntime(  818): 	... 11 more
```

**Comment by shubhral** [comment]
As the exception message suggests, this crash happens when there is no compatible Truecaller client available on the device.

Make sure you're using `TruecallerSdk.isUsable` properly as mentioned in the [example section](https://github.com/truecaller/flutter-sdk/blob/master/README.md) of the Readme to detect the presence of a compatible client **just before** calling the `TruecallerSdk.getProfile` method. 

For your reference, correct usage of `isUsable` with `getProfile` should be like this - 

```
//initialize the SDK
TruecallerSdk.initializeSDK(sdkOptions: TruecallerSdkScope.SDK_OPTION_WITHOUT_OTP);

//check isUsable just before calling getProfile
TruecallerSdk.isUsable.then((isUsable) => 
         isUsable ? TruecallerSdk.getProfile : print("Not Usable"));
```
So the above snippet would print "Not Usable" in your console logs since you don't have Truecaller app installed on your device. 

You can also find the example implementations [here](https://github.com/truecaller/flutter-sdk/tree/master/example).
