### ISSUE TITLE
RuntimeException: Please call init() on TruecallerSDK first

### ISSUE THREAD

**Issue by vkbaloda** [truecaller/flutter-sdk#30]
Hey guys, I'm getting this error on my crashlytics, not able to reproduce it and so just couldn't understand why the error may be coming. The error creates a crash. I'm using the implementation as shown in the example app. Can somebody please give some direction to avoid it.

error logs:
```Caused by java.lang.RuntimeException: Please call init() on TruecallerSDK first
       at com.truecaller.android.sdk.TruecallerSDK.getInstance(TruecallerSDK.java:108)
       at com.truecallersdk.TruecallerSdkPlugin.onActivityResult(TruecallerSdkPlugin.kt:311)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:703)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:508)
       at android.app.Activity.dispatchActivityResult(Activity.java:8509)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5135)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4535)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4580)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2131)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8019)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Please tell if any other info is needed

**Comment by parth0907** [comment]
Hi @vkbaloda 

Thanks for writing in! 

As the crash suggests, it's because the SDK has not been initialised and hence it's leading to a RuntimeException. I would request you to check for an instance where the Truecaller SDK is not initialised but some method exposed by the SDK is being called. 

For ex: To reproduce this crash you can simply call getProfile()/isUsable() exposed by the SDK without initialising it first. 

In case of any further questions, please feel free to reach us via our support channel https://developer.truecaller.com/support for a faster and dedicated response.

Regards, 
Parth

**Comment by preetpatel21** [comment]
I get the same error and also i call init() method first before the TruecallerSDK.getInstance().isUsable() this use.
So Could you please assist me?

**Comment by MayankJunglee2020** [comment]
Facing the same, not able to reproduce the issue but getting lots of crashes reported on crashlytics dashboard. @vkbaloda @parth0907 @preetpatel21 please help here.

**Comment by Rohit-joshi-apna** [comment]
Facing the same issue, Any updates on the issue ?

**Comment by vkbaloda** [comment]
Just giving an update on my side. I wasn't able to solve it by then. Right now, I'm working on a different project & not using this package & so not dealing with this issue. 
@parth0907 Yes, the SDK.initialise method was being called (with await) before other methods (rechecked now also), as we were using the example app only; so the error must be from this package code I guess, as others also suggested.
Sorry for not able to help in diagnosing it further, right now.

**Comment by gauravgupta0194** [comment]
Facing the same issue, Any updates on the issue ?

**Comment by singhpratham72** [comment]
Any updates? The documentation provided does not call `await` on `TcSdk.initializeSDK(sdkOption)`, is this related to that?
